version: "1.0"
services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    command: start-dev --import-realm --health-enabled=true --metrics-enabled=true
    ports:
      - "8080:8080"
      - "9000:9000"
