server:
  port: 8000

spring:
  application:
    name:
      spring-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm

logging:
  level:
    org.springframework.security: DEBUG