server:
  port: ${PORT:8000}

spring:
  application:
    name: spring-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_URL:http://localhost:8080/realms/myrealm}

cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

logging:
  level:
    org.springframework.security: DEBUG